const {test}=require('node:test'),assert=require('node:assert/strict');
const {handle,identity,validate,date,empty}=require('./core');
function database(){const data=new Map();let chain=Promise.resolve();function ref(path){return {id:path.split('/').at(-1),path,collection:c=>query(path+'/'+c),get:async()=>({exists:data.has(path),data:()=>structuredClone(data.get(path))})};}function query(path,field='__name__',desc=false,size=100,after=null){return {doc:id=>ref(path+'/'+id),orderBy:(f,d)=>query(path,f,d==='desc',size,after),limit:n=>query(path,field,desc,n,after),startAfter:a=>query(path,field,desc,size,a),get:async()=>({docs:[...data].filter(([k])=>k.startsWith(path+'/')&&!k.slice(path.length+1).includes('/')).map(([k,v])=>({id:k.split('/').at(-1),data:()=>structuredClone(v)})).sort((a,b)=>{const x=field==='__name__'?a.id:a.data()[field],y=field==='__name__'?b.id:b.data()[field];return (x<y?-1:x>y?1:0)*(desc?-1:1);}).filter(d=>!after||d.id>after).slice(0,size)})};}return {data,collection:c=>query(c),runTransaction:fn=>{const result=chain.then(async()=>{const writes=[];const tx={get:r=>r.get(),set:(r,v,o)=>writes.push(()=>data.set(r.path,o?.merge?{...data.get(r.path),...structuredClone(v)}:structuredClone(v))),update:(r,v)=>writes.push(()=>data.set(r.path,{...data.get(r.path),...structuredClone(v)})),create:(r,v)=>{if(data.has(r.path))throw Error('exists');writes.push(()=>data.set(r.path,structuredClone(v)));}};const out=await fn(tx);writes.forEach(f=>f());return out;});chain=result.catch(()=>{});return result;}};}
const teacher={uid:'teacher1',name:'합성 강사',admin:false},admin={uid:'admin1',name:'합성 관리자',admin:true};
const body=()=>({...empty(),rows:[{id:1,name:'합성 학생',start:840,end:900,type:'개별',note:'보강'}],subjects:{14:'수학'}});
const req=(action,revision=0,data=body(),operationId='operation-12345678')=>({action,date:'2026-10-01',revision,data,operationId});
test('access is active account based; no client role or owner spoofing',async()=>{assert.throws(()=>identity({role:'ADMIN',status:'DISABLED'}, {},{},'a'));assert.throws(()=>identity({role:'TEACHER',status:'ACTIVE',name:'A'},{},{apps:{liveTimetable:false}},'a'));assert.equal(identity({role:'STAFF',status:'ACTIVE',name:'A'},{},{permissions:{canManageSchedules:true}},'a').admin,true);const db=database();await assert.rejects(handle(db,teacher,{action:'list',date:'2026-10-01'}),/FORBIDDEN/);await assert.rejects(handle(db,teacher,{action:'versions',uid:'other',date:'2026-10-01'}),/FORBIDDEN/);await handle(db,teacher,{...req('saveDraft'),uid:'other'});assert([...db.data.keys()].every(k=>k.includes('/teacher1')));});
test('strict dates, rows, subjects and overlapping intervals',()=>{assert.throws(()=>date('2026-02-30'));assert.throws(()=>validate({...body(),rows:[...body().rows,...body().rows]}));assert.throws(()=>validate({...body(),subjects:{'24':'bad'}}));assert.throws(()=>validate({...body(),rows:[...body().rows,{...body().rows[0],id:2,start:850}]}),/OVERLAP/);assert.equal(validate({...body(),rows:[...body().rows,{...body().rows[0],id:2,start:900,end:960}]}).rows.length,2);assert.throws(()=>validate({...body(),rows:[{...body().rows[0],end:1441}]}));});
test('draft revisions, idempotent retry, multi-tab conflict and date isolation',async()=>{const db=database();assert.equal((await handle(db,teacher,req('saveDraft'))).revision,1);assert.equal((await handle(db,teacher,req('saveDraft'))).revision,1);await assert.rejects(handle(db,teacher,req('saveDraft',0,body(),'operation-22222222')),/CONFLICT/);await assert.rejects(handle(db,teacher,req('saveDraft',1,{...body(),subjects:{} })),/INVALID_OPERATION/);const draft=await handle(db,teacher,{action:'draft',date:'2026-10-01'});assert.equal(draft.draft.rows[0].note,'보강');assert.equal((await handle(db,teacher,{action:'draft',date:'2026-10-02'})).draft.rows.length,0);});
test('immutable submissions, duplicate submit, per-version status and latest metadata',async()=>{const db=database();let one=await handle(db,teacher,req('submit'));assert.equal(one.version.number,1);assert.equal((await handle(db,teacher,req('submit'))).version.number,1);const data=body();data.subjects[14]='영어';let two=await handle(db,teacher,req('submit',1,data,'operation-22222222'));assert.equal(two.version.number,2);let all=await handle(db,admin,{action:'versions',uid:teacher.uid,date:'2026-10-01'});assert.equal(all.versions[1].subjects[14],'수학');let status={action:'status',uid:teacher.uid,date:'2026-10-01',operationId:one.version.operationId,statusRevision:0,state:'반영 완료'};await assert.rejects(handle(db,teacher,status),/FORBIDDEN/);await handle(db,admin,status);await handle(db,admin,status);const list=await handle(db,admin,{action:'list',date:'2026-10-01'});assert.equal(list.items[0].latest.state,'미확인');assert(!JSON.stringify(list).includes('합성 학생'));await assert.rejects(handle(db,admin,{...status,state:'확인 중'}),/CONFLICT/);});
test('submit refuses empty or uncommitted forms; concurrent writer only one wins',async()=>{const db=database();await assert.rejects(handle(db,teacher,req('submit',0,empty())),/UNFINISHED_INPUT/);const d=body();d.form[0]='unfinished';await assert.rejects(handle(db,teacher,req('submit',0,d)),/UNFINISHED_INPUT/);const result=await Promise.allSettled([handle(db,teacher,req('saveDraft')),handle(db,teacher,req('saveDraft',0,body(),'operation-22222222'))]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);});
module.exports={database};
