const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function harness(){
 class Element{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.textContent='';this.hidden=false;}append(...nodes){this.children.push(...nodes);}replaceChildren(){this.children=[];}setAttribute(k,v){this[k]=v;}contains(e){return e===this||this.children.some(c=>c.contains?.(e));}querySelectorAll(){return this.children.flatMap(c=>[...(c.dataset?.focus?[c]:[]),...(c.querySelectorAll?.()||[])]);}focus(){document.activeElement=this;}}
 const document={body:new Element('body'),head:new Element('head'),createElement:t=>new Element(t),createTextNode:t=>({textContent:t}),activeElement:{value:'unsaved synthetic edit'},querySelectorAll:()=>[]};const editor=document.activeElement;
 let authCallback,latest,refreshes=0,unsub=0,syncStops=0;const timers=new Map();let timer=0;const actions=[];const user={uid:'synthetic',getIdToken:async()=>''};const auth={currentUser:user,onAuthStateChanged:fn=>{authCallback=fn;return ()=>unsub++;}};
 const context={document,AbortController,TextDecoder,Date,Map,Array,JSON,String,Error,Promise,setTimeout:fn=>{timers.set(++timer,fn);return timer;},clearTimeout:id=>timers.delete(id),setInterval:()=>1,clearInterval(){},authState:{loggedIn:true,isLookup:false,loginId:'synthetic'},currentSheetName:'2026-10-04',attendanceDateKey:()=> '2026-10-04',loadNotice(){},stopLiveNotice(){},getLiveFirebaseAuth:async()=>auth,getLiveFirebaseFirestore:async()=>({}),refreshData:()=>refreshes++};context.window={addEventListener(){},createDotAlertSync:opts=>{latest=opts;return {start(){opts.authorize();},stop(){syncStops++;}};}};context.fetch=async(_,opts)=>{const b=JSON.parse(opts.body);actions.push(b);return {ok:true,json:async()=>({ok:true,uid:'synthetic'})};};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/dot-alert-client.js','utf8'),context);
 return {context,document,editor,timers,auth,actions,logout(){auth.currentUser=null;authCallback(null);},get syncStops(){return syncStops;},get unsub(){return unsub;},get refreshes(){return refreshes;},push(items,states={}){latest.onState({items,states,syncedAt:Date.now(),connection:'연결됨'});},finish(){latest.onFailure(Error('disconnected'));},host:()=>document.body.children[0]};
}
const tick=()=>new Promise(r=>setImmediate(r));
const alert={id:'a'.repeat(64),studentName:'합성학생',targetDate:'2026-10-04',classTime:'17:00',message:'합성 검사',revision:2,state:'RESOLVED',expiresAt:Date.now()+100000};
test('snapshot updates only alert area, stale revision rejected, reconnect and logout cleanup',async()=>{const h=harness();h.context.loadNotice();await tick();h.push([alert]);await tick();assert.equal(h.refreshes,0);assert.equal(h.document.activeElement,h.editor);assert.equal(h.editor.value,'unsaved synthetic edit');let content=()=>h.host().children.flatMap(x=>x.children||[]).map(x=>x.textContent).join(' ');assert.match(content(),/RESOLVED/);h.push([{...alert,revision:1,state:'NEW'}]);await tick();assert.match(content(),/RESOLVED/);h.finish();await tick();assert.equal(h.timers.size,0);assert.doesNotMatch(content(),/합성학생/);h.logout();assert.ok(h.syncStops>=1);assert.equal(h.unsub,1);assert.equal(h.host().hidden,true);assert.equal(h.timers.size,0);});

test('new alert, repeated read and dismiss stay user-local; resolve sends current revision',async()=>{const h=harness();h.context.loadNotice();await tick();h.push([{...alert,state:'NEW'}]);await tick();const buttons=()=>h.host().querySelectorAll();const action=a=>buttons().find(e=>e.dataset.focus===alert.id+':'+a);assert.ok(h.host().children.some(e=>e['aria-label']==='dot 말풍선'));await action('read').onclick();await action('read').onclick();assert.match(h.host().children.flatMap(e=>e.children||[]).map(e=>e.textContent).join(' '),/읽음/);await action('dismiss').onclick();assert.ok(!h.host().children.some(e=>e['aria-label']==='dot 말풍선'));assert.ok(action('resolve'));action('resolve').focus();await action('resolve').onclick();assert.equal(h.actions.at(-1).revision,2);h.push([{...alert,revision:3,state:'RESOLVED'}]);await tick();assert.equal(h.document.activeElement.dataset.focus,alert.id+':resolve');assert.equal(h.refreshes,0);h.logout();});

test('cell navigation uses current grid identity, school and hour; ambiguous names never select the wrong cell',async()=>{const h=harness();let selected=0;const cell=(name,school,hour)=>({dataset:{studentIdentity:JSON.stringify([name,school])},closest:()=>({dataset:{hour}}),scrollIntoView:()=>selected++});h.document.querySelectorAll=selector=>{assert.equal(selector,'#scheduleTable .student-item.is-student');return [cell('합성학생','합성중3','17'),cell('합성학생','다른중3','17'),cell('합성학생','합성중3','18')];};h.context.loadNotice();await tick();h.push([{...alert,school:'합성중',grade:'3',classTime:'17:30'}]);await tick();const button=()=>h.host().children.flatMap(e=>e.children||[]).find(e=>e.textContent==='시간표 셀');button().onclick();assert.equal(selected,1);assert.equal(h.document.activeElement,h.editor);h.document.querySelectorAll=()=>[cell('합성학생','합성중3','17'),cell('합성학생','합성중3','17')];button().onclick();assert.equal(selected,1);assert.ok(h.host().children.some(e=>String(e.textContent).includes('여러 개')));h.logout();});
