const {test}=require('node:test');const assert=require('node:assert/strict');const {createDotAlertSync}=require('./dot-alert-sync.js');const tick=()=>new Promise(r=>setImmediate(r));
function world(){const subscriptions=[],rooms=new Map(),locks=new Map();class Channel{constructor(name){this.name=name;(rooms.get(name)||rooms.set(name,new Set()).get(name)).add(this);}postMessage(data){for(const other of rooms.get(this.name))if(other!==this)queueMicrotask(()=>other.onmessage?.({data}));}close(){rooms.get(this.name).delete(this);}}
 const nav={locks:{request(name,{signal},callback){return new Promise((resolve,reject)=>{const queue=locks.get(name)||locks.set(name,[]).get(name);const task={async run(){task.active=true;try{resolve(await callback());}catch(e){reject(e);}finally{queue.shift();queue[0]?.run();}}};queue.push(task);signal.addEventListener('abort',()=>{if(task.active)return;const i=queue.indexOf(task);if(i>=0)queue.splice(i,1);reject(Object.assign(Error(),{name:'AbortError'}));});if(queue.length===1)task.run();});}}};
 const db={collection(name){const query={doc(){return query;},collection(){return query;},orderBy(){return query;},limit(n){assert.equal(n,200);return query;},onSnapshot(opts,next,error){if(typeof opts==='function'){error=next;next=opts;}else assert.equal(opts.includeMetadataChanges,true);const s={kind:name==='liveTimetableDotUserState'?'states':name==='liveTimetableDotAlerts_sedubanpo'?'alerts':'identity',next,error,active:true};subscriptions.push(s);return ()=>s.active=false;}};return query;}};
 function tab(uid='synthetic',useLocks=true){let visibility;const doc={hidden:false,addEventListener(type,fn){visibility=fn;},removeEventListener(){visibility=null;}};const timers=new Set(),state=[],failure=[];let calls=0,allowed=true,hanging=false;const sync=createDotAlertSync({uid,db,document:doc,navigator:useLocks?nav:{},BroadcastChannel:Channel,authorize:async()=>{calls++;if(!allowed)throw Error('403');if(hanging)return new Promise(()=>{});return {uid};},onState:s=>state.push(s),onFailure:e=>failure.push(e),setTimeout:fn=>{timers.add(fn);return fn;},clearTimeout:fn=>timers.delete(fn)});return {sync,state,failure,timers,get calls(){return calls;},deny(){allowed=false;},hang(){hanging=true;},hide(){doc.hidden=true;visibility();},show(){doc.hidden=false;visibility();},check(){for(const fn of [...timers]){timers.delete(fn);fn();}}};}
 function push(kind,items){for(const s of subscriptions.filter(s=>s.active&&s.kind===kind))s.next({docs:items.map(x=>({id:x.id,data:()=>x})),metadata:{fromCache:false}});}
 return {tab,subscriptions,push};}
test('idle event subscription never rereads data or holds HTTP SSE; guarded auth and snapshots are separate',async()=>{const w=world(),a=w.tab();a.sync.start();await tick();assert.equal(w.subscriptions.length,5);w.push('alerts',[]);w.push('states',[]);await tick();assert.equal(a.state.at(-1).items.length,0);for(let i=0;i<8;i++){a.check();await tick();}assert.equal(w.subscriptions.length,5);assert.equal(a.calls,9);w.push('alerts',[{id:'synthetic',revision:1}]);await tick();assert.equal(a.state.at(-1).items[0].revision,1);assert.equal(w.subscriptions.length,5);a.sync.stop();assert.ok(w.subscriptions.every(s=>!s.active));assert.equal(a.timers.size,0);});
test('visible tabs share one leader; hidden tab releases and visible follower takes over; own states are broadcast',async()=>{const w=world(),a=w.tab(),b=w.tab();a.sync.start();b.sync.start();await tick();assert.equal(w.subscriptions.length,5);w.push('alerts',[{id:'a',revision:2}]);w.push('states',[{id:'a',read:true}]);await tick();assert.equal(b.state.at(-1).states.a.read,true);assert.equal(b.timers.size,0);a.hide();await tick();assert.equal(w.subscriptions.filter(s=>s.active).length,5);assert.equal(w.subscriptions.length,10);b.hide();await tick();assert.ok(w.subscriptions.every(s=>!s.active));a.show();await tick();assert.equal(w.subscriptions.filter(s=>s.active).length,5);a.sync.stop();b.sync.stop();await tick();assert.ok(w.subscriptions.every(s=>!s.active));});
test('revoked auth and permission denied halt all same-user tabs without retry loops; other users stay isolated',async()=>{const w=world(),a=w.tab(),b=w.tab(),other=w.tab('other');a.sync.start();b.sync.start();other.sync.start();await tick();assert.equal(w.subscriptions.filter(s=>s.active).length,10);a.deny();a.check();await tick();assert.equal(a.failure.length,1);assert.equal(b.failure.length,1);assert.equal(other.failure.length,0);assert.equal(w.subscriptions.filter(s=>s.active).length,5);assert.equal(a.timers.size,0);assert.equal(b.timers.size,0);w.subscriptions.find(s=>s.active).error(Error('permission-denied'));await tick();assert.equal(other.failure.length,1);assert.ok(w.subscriptions.every(s=>!s.active));a.sync.stop();b.sync.stop();other.sync.stop();});
test('logout or hide while authorization is pending cannot attach a late listener',async()=>{let resolve,authSignal;let listeners=0;const doc={hidden:false,addEventListener(){},removeEventListener(){}};const sync=createDotAlertSync({uid:'synthetic',document:doc,navigator:{},BroadcastChannel:null,db:{collection(){listeners++;throw Error('late');}},authorize:signal=>{authSignal=signal;return new Promise(r=>resolve=r);},onState(){},onFailure(){assert.fail('late failure');}});sync.start();sync.stop();assert.equal(authSignal.aborted,true);resolve({uid:'synthetic'});await tick();assert.equal(listeners,0);});

test('without Web Locks the supported fallback stays event-based but each visible tab pays for its own subscriptions',async()=>{const w=world(),a=w.tab('synthetic',false),b=w.tab('synthetic',false);a.sync.start();b.sync.start();await tick();assert.equal(w.subscriptions.filter(s=>s.active).length,10);a.hide();await tick();assert.equal(w.subscriptions.filter(s=>s.active).length,5);a.sync.stop();b.sync.stop();assert.ok(w.subscriptions.every(s=>!s.active));});

test('unresponsive authentication fails closed by deadline and removes all subscriptions',async()=>{const w=world(),a=w.tab();a.sync.start();await tick();a.hang();a.check();await tick();assert.equal(a.failure.length,0);a.check();await tick();assert.equal(a.failure.length,1);assert.ok(w.subscriptions.every(s=>!s.active));assert.equal(a.timers.size,0);a.sync.stop();});
